@LAZYGLOBAL OFF.
WAIT UNTIL SHIP:UNPACKED. 
RUNONCEPATH("../../common/infos").

LOCAL LIGHT_BAR_LIGHTS TO SHIP:PARTSTAGGED("LIGHTBAR").
LOCAL L1 TO LIGHT_BAR_LIGHTS[0].
LOCAL LIGHT_MODULE TO L1:GETMODULE("ModuleLight").

// DESCRIBE_MODULE_TO_FILE(LIGHT_MODULE).

LIGHT_MODULE:SETFIELD("light color", "#ffffff").
// DESCRIBE_SUFFIXNAMES_TO_FILE(LIGHT_MODULE).

// DESCRIBE_PART_ITEM_TO_FILE(L1:GETMODULE("ModuleLight"):GETFIELD("light color")).