FUNCTION WAIT_UNTIL_OREINTED { 
    PARAMETER ANGLE_ERR_THRESHOLD IS 2.25.
    PARAMETER ANGULAR_MAG_THRESHOLD IS 2.
    WAIT UNTIL ABS(STEERINGMANAGER:ANGLEERROR) < ANGLE_ERR_THRESHOLD AND SHIP:ANGULARVEL:MAG < ANGULAR_MAG_THRESHOLD.
}

GLOBAL FUNCTION RESET_TORQUE { 
    LOCAL TORQUE_FACTOR TO 1.

    SET STEERINGMANAGER:YAWTORQUEFACTOR TO TORQUE_FACTOR.
    SET STEERINGMANAGER:PITCHTORQUEFACTOR TO TORQUE_FACTOR.
    SET STEERINGMANAGER:ROLLTORQUEFACTOR TO TORQUE_FACTOR.
}