FUNCTION LINEAR_FALLOFF {
    PARAMETER FALLOFF_RATE.
    PARAMETER ERR_AMT.    
    PARAMETER MIN_ERR IS 0.        

    RETURN FALLOFF_RATE * (ERR_AMT - MIN_ERR).
}

FUNCTION LINEAR_FUNC { 
    PARAMETER M.
    PARAMETER X.
    PARAMETER B.

    RETURN (M * X) + B.
}