
// TERMINAL 

GLOBAL FLIGHT_STATUS TO "UNKNOWN".

GLOBAL FUNCTION DISPLAY_STATUS_IN_BACKGROUND { 
    PARAMETER TITLE.
    PARAMETER UPDATE_RATE TO 0.75.

    UNTIL FALSE { 
        CLEARSCREEN.
        PRINT "==== " + TITLE + " ====".
        PRINT "FLIGHT STATUS: " + FLIGHT_STATUS.
        WAIT UPDATE_RATE.
    }
}