
FUNCTION CIRCULARIZATION_CONTROLLER {     

    FUNCTION CIRCULARIZE { 
        PARAMETER USE_PERIAPSIS.

        // LOCAL TARGET_ALTITUDE 
        // IF NOT USE_PERIAPSIS { 

        // }
        // TODO: CREATE MANUEVER

        LOCAL TIME_TO_NODE TO TIME:SECONDS + SHIP:ORBIT:ETA:APOAPSIS.
        LOCAL MANV TO NODE(TIME_TO_NODE).
        ADD MANV.

        // EXEC
    }

    RETURN LEXICON(
        "CIRCULARIZE", CIRCULARIZE@
    ).
}